
  episode configuration:

    episode climax: 

    episode matters of desire:
      - episode matters of desire dn: 
        episode matters of desire desire: 
        episode matters of desire opponent:
          episode matters of desire dn: 
          episode matters of desire desire: 
        episode matters of desire risk: 
        episode matters of desire results: 

    episode value change:
      - episode value change dn: 
        episode value change item: 
        episode value change change: .

    episode world-building:
      - episode world-building item: 
      - episode world-building item: 
      - episode world-building item: 

    episode notes:
      - 

