
  episode configuration:

    episode climax: 

    episode desire:
      - episode desire dn: 
        episode desire desire: 
        episode desire conflict:
          - episode desire conflict-dn: 
            episode desire conflict-desire: 
        episode desire risk: 
        episode desire results: 
        episode desire gap: 

    episode value-change:
      - episode value-change dn: 
        episode value-change item: 
        episode value-change change: .

    episode world-building:
      - episode world-building item: 
      - episode world-building item: 
      - episode world-building item: 

    episode new-proper-noun:
      - episode new-proper-noun item: 

    episode notes:
      - 

